name: qnap-nas-setup
version: "3"

services:
  init-letsencrypt:
    image: liverwust/qnap-nas-setup:8
    container_name: qnap-nas-setup
    volumes:
      - ddns_config:/updater/config
      - letsencrypt:/etc/letsencrypt
      - nginx_confd:/etc/nginx/conf.d
      - nginx_www:/var/www
    environment:
      QNAP_NAS_DOMAINS: 'example.com:www.example.com'
      ## Change this to "production" after obtaining a first certificate...
      ## ... rerun this container/app, but COMMENT OUT issue-first-certbot
      QNAP_NAS_TEMPLATE: production

  issue-first-certbot:
    image: certbot/certbot:latest
    container_name: issue-first-certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - nginx_www:/var/www
    # Remember to edit the domains, email, and remove --staging
    entrypoint: '/bin/sh -c "certbot certonly --webroot -w /var/www/certbot --staging --agree-tos --force-renewal -d example.com -d www.example.com --email sample@example.com --verbose"'

volumes:
  ddns_config:
    external: true
  letsencrypt:
    external: true
  nginx_confd:
    external: true
  nginx_www:
    external: true
