---
# Handle changes related to the wicked network manager

- name: wicked ifreload (if this fails, check the IP address)
  ansible.builtin.command: "/usr/sbin/wicked ifreload {{ ansible_default_ipv4.interface }}"
  # This may timeout as network params are change; check every 6 seconds for
  # connectivity, and wait for 60 total before failing
  async: 60
  poll: 6

- name: netconfig update (if this fails, check the IP address)
  ansible.builtin.command: /sbin/netconfig update --force-replace
  # This may timeout as network params are change; check every 6 seconds for
  # connectivity, and wait for 60 total before failing
  async: 60
  poll: 6

...
