---
name: bacula-on-qnap

services:
  # https://hub.docker.com/_/postgres
  database:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    volumes:
      - database-data:/var/lib/postgresql/data
      - /share/Container/user-config/database/initdb.d:/docker-entrypoint-initdb.d:ro
    secrets:
      - postgres-bacula-password
      - postgres-password

  bacula-dir:
    image: liverwust/bacula-dir:bookworm-13.0.4-1
    restart: always
    volumes:
      - /share/Container/user-config/bacula-dir/archive:/opt/bacula/archive
      - /share/Container/user-config/bacula-dir/bsr:/opt/bacula/bsr
      - /share/Container/user-config/bacula-dir/etc:/opt/bacula/etc
      - /share/Container/user-config/bacula-dir/log:/opt/bacula/log
      - /share/Container/user-config/bacula-dir/working:/opt/bacula/working

volumes:
  database-data:

secrets:
  # Note: with Docker Desktop, it is necessary to add one of these parent
  # directories to the list of File Sharing locations:
  # https://docs.docker.com/desktop/settings-and-maintenance/settings/#file-sharing

  # The superuser password for the postgresql database.
  postgres-bacula-password:
    file: /share/Container/user-config/database/postgres-bacula-password.txt

  # The user password for the Bacula user accessing PostgreSQL
  postgres-password:
    file: /share/Container/user-config/database/postgres-password.txt
