all:
  vars:
  children:
    nas:
      hosts:
        brikblok:
          ansible_become_password: >-
            {{ lookup('bitwarden.secrets.lookup',
                      '0fb7325e-0cec-4c4c-bd32-b3490101997f') }}

    dreamcompute:
      vars:
        ansible_user: debian
        dreamhost_control_openstack_auth_url: >-
          {{ lookup('bitwarden.secrets.lookup',
                    '1c452ae9-7795-4bed-9049-b34500629d9c') }}
        dreamhost_control_openstack_password: >-
          {{ lookup('bitwarden.secrets.lookup',
                    '56dfd850-5420-4901-bfc0-b34500624030') }}
        dreamhost_control_openstack_project_name: >-
          {{ lookup('bitwarden.secrets.lookup',
                    'ef1237b6-f31d-494e-bece-b3450062d52d') }}
        dreamhost_control_openstack_username: >-
          {{ lookup('bitwarden.secrets.lookup',
                    'ab7e13be-95b3-47b0-be25-b3450062720a') }}
        dreamhost_control_plane_endpoint: control.cluster.wust.us
        dreamhost_control_plane_floating_ip: >-
          {{ lookup('bitwarden.secrets.lookup',
                    '3a6c666b-4d59-4666-9493-b35000f7f057') }}
        dreamhost_data_plane_endpoint: wust.us
        dreamhost_data_plane_floating_ip: >-
          {{ lookup('bitwarden.secrets.lookup',
                    '3839fda2-d53c-4deb-98fc-b35000f80daa') }}
        dreamhost_dns_api_key: '{{ lookup("ansible.builtin.env", "DREAMHOST_DNS_API_KEY") }}'
        dreamhost_dns_zone: wust.us
        dreamhost_instance_image: "Debian-12"
        dreamhost_network_private_range: >-
          {{ lookup('bitwarden.secrets.lookup',
                    '7c19bcfc-f2f6-4b69-95fd-b34100593a6f') }}
        dreamhost_private_key: '{{ lookup("ansible.builtin.env", "HOME") }}/.ssh/id_cloud'
        dreamhost_public_key: '{{ dreamhost_private_key }}.pub'
        dreamhost_user_password_hash: >-
          {{ lookup('bitwarden.secrets.lookup',
                    'f499e16a-f16d-4688-8a40-b3450047ebd9') }}
        dreamhost_version_crio: v1.33
        dreamhost_version_kubernetes: v1.33
        # This is an emergent property of the dreamhost_instance_image
        dreamhost_volume_device: /dev/disk/by-path/virtio-pci-0000:00:05.0

        dreamhost_security_group_rules:
          - description: Inbound SSH from the Ansible Control Node IPv4
            direction: ingress
            ether_type: IPv4
            port_range_min: 22
            port_range_max: 22
            protocol: tcp
            remote_ip_prefix: "{{ ansible_control_node_external_ipv4 }}/32"

          - description: Kubernetes API service from the Ansible Control Node IPv4
            direction: ingress
            ether_type: IPv4
            port_range_min: 6443
            port_range_max: 6443
            protocol: tcp
            remote_ip_prefix: "{{ ansible_control_node_external_ipv4 }}/32"

          - description: Inter-node SSH from the private network
            direction: ingress
            ether_type: IPv4
            port_range_min: 22
            port_range_max: 22
            protocol: tcp
            remote_ip_prefix: "{{ dreamhost_network_private_range }}"

          # https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/7/html/high_availability_add-on_reference/s1-firewalls-haar
          - description: pcsd between nodes from private network
            direction: ingress
            ether_type: IPv4
            port_range_min: 2224
            port_range_max: 2224
            protocol: tcp
            remote_ip_prefix: "{{ dreamhost_network_private_range }}"

          - description: corosync between nodes from private network
            direction: ingress
            ether_type: IPv4
            port_range_min: 4505
            port_range_max: 4505
            protocol: udp
            remote_ip_prefix: "{{ dreamhost_network_private_range }}"

          - description: Kubernetes API service from the private network
            direction: ingress
            ether_type: IPv4
            port_range_min: 6443
            port_range_max: 6443
            protocol: tcp
            remote_ip_prefix: "{{ dreamhost_network_private_range }}"

          - description: "Kubelet API service from the private network"
            direction: ingress
            ether_type: IPv4
            port_range_min: 10250
            port_range_max: 10250
            protocol: tcp
            remote_ip_prefix: "{{ dreamhost_network_private_range }}"

          - description: Inbound ICMP4 (ping and friends)
            direction: ingress
            ether_type: IPv4
            protocol: icmp

          - description: Inbound ICMP6 (ping and friends)
            direction: ingress
            ether_type: IPv6
            protocol: icmpv6

          - description: Egress IPv4 (no restriction)
            direction: egress
            ether_type: IPv4
            protocol: any

          - description: Egress IPv4 (no restriction)
            direction: egress
            ether_type: IPv6
            protocol: any

      children:
        dreamcompute_control:
          hosts:
            control1.cluster.wust.us:
              dreamhost_volume_key: >-
                {{ lookup('bitwarden.secrets.lookup',
                          '2c41c46d-ff42-41b9-9601-b341004810c7') }}
              k8s_nodes_hacluster_password_hash: >-
                {{ lookup('bitwarden.secrets.lookup',
                          '73543ae0-a32f-4af7-92cd-b3450049a06a') }}
              k8s_nodes_hacluster_password_plain: >-
                {{ lookup('bitwarden.secrets.lookup',
                          '7a5cb334-e633-4db1-9472-b3450049bcbc') }}

            control2.cluster.wust.us:
              dreamhost_volume_key: >-
                {{ lookup('bitwarden.secrets.lookup',
                          'cdec8106-a73c-418c-b15c-b34100497ee7') }}
              k8s_nodes_hacluster_password_hash: >-
                {{ lookup('bitwarden.secrets.lookup',
                          'f5c4ec16-f46d-4247-9d5b-b3450049d5ab') }}
              k8s_nodes_hacluster_password_plain: >-
                {{ lookup('bitwarden.secrets.lookup',
                          'ba61ff0f-ce83-42c5-913d-b3450049f3bc') }}

            control3.cluster.wust.us:
              dreamhost_volume_key: >-
                {{ lookup('bitwarden.secrets.lookup',
                          'e9beaf4f-8742-4625-94d1-b3410049c833') }}
              k8s_nodes_hacluster_password_hash: >-
                {{ lookup('bitwarden.secrets.lookup',
                          'c02aa2f1-8c00-4e71-a518-b345004a120f') }}
              k8s_nodes_hacluster_password_plain: >-
                {{ lookup('bitwarden.secrets.lookup',
                          '734a7bbf-dd22-4336-a324-b345004a2b62') }}

          vars:
            dreamhost_instance_flavor: "gp1.lightspeed"
            dreamhost_volume_size: 20
            k8s_nodes_is_control: true
            k8s_nodes_ssh_keys:
              - algorithm: dsa
                private_key: |
                  {{ lookup('bitwarden.secrets.lookup',
                            'cb560387-96ef-48ed-959a-b34300673bd5') }}
                public_key: |
                  {{ lookup('bitwarden.secrets.lookup',
                            'b753e47c-42d1-4ef8-8d88-b343006765b1') }}
              - algorithm: ecdsa
                private_key: |
                  {{ lookup('bitwarden.secrets.lookup',
                            '0feb2f30-dc05-4976-8d99-b34300678fd8') }}
                public_key: |
                  {{ lookup('bitwarden.secrets.lookup',
                            '3574bd04-d271-4bba-97d1-b3430067b013') }}
              - algorithm: ed25519
                private_key: |
                  {{ lookup('bitwarden.secrets.lookup',
                            '91e3d1fa-8bb1-4507-9402-b3430067cfc1') }}
                public_key: |
                  {{ lookup('bitwarden.secrets.lookup',
                            'e931a770-40f1-4e87-aeed-b3430067f4a7') }}
              - algorithm: rsa
                private_key: |
                  {{ lookup('bitwarden.secrets.lookup',
                            'eb9b5cb9-7b76-4332-ac73-b343006813fc') }}
                public_key: |
                  {{ lookup('bitwarden.secrets.lookup',
                            'd7951db9-9fab-4909-be59-b343006833ab') }}

        dreamcompute_worker:
          hosts:
            worker1.cluster.wust.us:
              dreamhost_volume_key: >-
                {{ lookup('bitwarden.secrets.lookup',
                          '51ce3131-a26c-4087-91aa-b341004a1d4f') }}

            worker2.cluster.wust.us:
              dreamhost_volume_key: >-
                {{ lookup('bitwarden.secrets.lookup',
                          '4c2cce2b-5d4c-4b52-8673-b341004a47af') }}

            worker3.cluster.wust.us:
              dreamhost_volume_key: >-
                {{ lookup('bitwarden.secrets.lookup',
                          'd326d48d-0586-4ba5-9f86-b341004a5c68') }}

          vars:
            dreamhost_instance_flavor: "gp1.lightspeed"
            dreamhost_volume_size: 20
            k8s_nodes_is_control: false
