all:
  children:
    nas:
      hosts:
        qnap:

    dreamcompute:
      hosts:
        microk8s.wust.us:
          ansible_user: debian
          dreamhost_dns_api_key: '{{ lookup("ansible.builtin.env", "DREAMHOST_DNS_API_KEY") }}'
          dreamhost_dns_zone: wust.us
          dreamhost_instance_flavor: "gp1.lightspeed"
          dreamhost_instance_image: "Debian-12"
          dreamhost_private_key: '{{ lookup("ansible.builtin.env", "HOME") }}/.ssh/id_cloud'
          dreamhost_public_key: '{{ dreamhost_private_key }}.pub'
          dreamhost_volume_size: 30
