all:
  vars:
    ansible_user: debian
    dreamhost_dns_api_key: '{{ lookup("ansible.builtin.env", "DREAMHOST_DNS_API_KEY") }}'
    dreamhost_dns_zone: wust.us
    dreamhost_floating_ip_control_name: control.cluster.wust.us
    dreamhost_instance_image: "Debian-12"
    dreamhost_network_private_range: >-
      {{ lookup('bitwarden.secrets.lookup'
                '7c19bcfc-f2f6-4b69-95fd-b34100593a6f') }}
    dreamhost_private_key: '{{ lookup("ansible.builtin.env", "HOME") }}/.ssh/id_cloud'
    dreamhost_public_key: '{{ dreamhost_private_key }}.pub'
    dreamhost_version_crio: v1.33
    dreamhost_version_kubernetes: v1.33
    # This is an emergent property of the dreamhost_instance_image
    dreamhost_volume_device: /dev/disk/by-path/virtio-pci-0000:00:05.0

    dreamhost_security_group_rules:
      - description: Inbound SSH from the Ansible Control Node IPv4
        direction: ingress
        ether_type: IPv4
        port_range_min: 22
        port_range_max: 22
        protocol: tcp
        remote_ip_prefix: "{{ ansible_control_node_external_ipv4 }}/32"

      - description: Inbound SSH from the Ansible Control Node IPv6
        direction: ingress
        ether_type: IPv6
        port_range_min: 22
        port_range_max: 22
        protocol: tcp
        remote_ip_prefix: "{{ ansible_control_node_external_ipv6 }}/128"

      - description: Kubernetes API service from the Ansible Control Node IPv4
        direction: ingress
        ether_type: IPv4
        port_range_min: 6443
        port_range_max: 6443
        protocol: tcp
        remote_ip_prefix: "{{ ansible_control_node_external_ipv4 }}/32"

      - description: Kubernetes API service from the Ansible Control Node IPv6
        direction: ingress
        ether_type: IPv6
        port_range_min: 6443
        port_range_max: 6443
        protocol: tcp
        remote_ip_prefix: "{{ ansible_control_node_external_ipv6 }}/128"

      - description: Kubernetes API service from the private network
        direction: ingress
        ether_type: IPv4
        port_range_min: 6443
        port_range_max: 6443
        protocol: tcp
        remote_ip_prefix: "{{ dreamhost_network_private_range }}"

      - description: "Kubelet API service from the private network"
        direction: ingress
        ether_type: IPv4
        port_range_min: 10250
        port_range_max: 10250
        protocol: tcp
        remote_ip_prefix: "{{ dreamhost_network_private_range }}"

      - description: Inbound ICMP4 (ping and friends)
        direction: ingress
        ether_type: IPv4
        protocol: icmp

      - description: Inbound ICMP6 (ping and friends)
        direction: ingress
        ether_type: IPv6
        protocol: icmpv6

      - description: Egress IPv4 (no restriction)
        direction: egress
        ether_type: IPv4
        protocol: any

      - description: Egress IPv4 (no restriction)
        direction: egress
        ether_type: IPv6
        protocol: any

  children:
    nas:
      hosts:
        qnap:

    dreamcompute:
      children:
        dreamcompute_control:
          hosts:
            control1.cluster.wust.us:
              dreamhost_volume_key: >-
                {{ lookup('bitwarden.secrets.lookup',
                          '2c41c46d-ff42-41b9-9601-b341004810c7') }}

            control2.cluster.wust.us:
              dreamhost_volume_key: >-
                {{ lookup('bitwarden.secrets.lookup',
                          'cdec8106-a73c-418c-b15c-b34100497ee7') }}

            control3.cluster.wust.us:
              dreamhost_volume_key: >-
                {{ lookup('bitwarden.secrets.lookup',
                          'e9beaf4f-8742-4625-94d1-b3410049c833') }}

          vars:
            dreamhost_instance_flavor: "gp1.lightspeed"
            dreamhost_volume_size: 20
            k8s_nodes_is_control: true

        dreamcompute_worker:
          hosts:
            worker1.cluster.wust.us:
              dreamhost_volume_key: >-
                {{ lookup('bitwarden.secrets.lookup',
                          '51ce3131-a26c-4087-91aa-b341004a1d4f') }}

            worker2.cluster.wust.us:
              dreamhost_volume_key: >-
                {{ lookup('bitwarden.secrets.lookup',
                          '4c2cce2b-5d4c-4b52-8673-b341004a47af') }}

            worker3.cluster.wust.us:
              dreamhost_volume_key: >-
                {{ lookup('bitwarden.secrets.lookup',
                          'd326d48d-0586-4ba5-9f86-b341004a5c68') }}

          vars:
            dreamhost_instance_flavor: "gp1.lightspeed"
            dreamhost_volume_size: 20
            k8s_nodes_is_control: false
