all:
  children:
    nas:
      hosts:
        qnap:

  hosts:
    dreamcompute:
      ansible_connection: ansible.builtin.local
      ansible_python_interpreter: '{{ lookup("ansible.builtin.pipe", "which python3") }}'
