---

- name: Apply DreamCompute configuration
  hosts: dreamcompute
  gather_facts: false
  roles:
    - us_wust.homeinfra.dreamhost

- name: Apply QNAP NAS configuration
  hosts: nas
  gather_facts: true
  roles:
    - us_wust.homeinfra.nas

...
