---

- name: Configure DreamCompute cloud resources
  hosts: localhost
  gather_facts: false
  become: false
  roles:
    - us_wust.homeinfra.dreamcompute

- name: Configure Kubernetes control nodes
  hosts: dreamcompute_control
  gather_facts: true
  become: true
  serial: 1
  roles:
    - us_wust.homeinfra.k8s_nodes

- name: Configure Kubernetes worker nodes
  hosts: dreamcompute_worker
  gather_facts: true
  become: true
  serial: 1
  roles:
    - us_wust.homeinfra.k8s_nodes

#- name: Apply QNAP NAS configuration
#  hosts: nas
#  gather_facts: true
#  roles:
#    - us_wust.homeinfra.nas
#
...
