---

- name: Get the IPv4 address of the Ansible Control Node
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: Store the IPv4 address as a hostvar
      ansible.builtin.set_fact:
        ansible_control_node_external_ipv4: |-
          {{ (lookup('ansible.builtin.url',
                     'https://api.ipify.org?format=json',
                     split_lines=False) |
              from_json).ip }}

- name: Configure DreamCompute cloud resources
  hosts: localhost
  gather_facts: false
  become: false
  roles:
    - us_wust.homeinfra.dreamhost

- name: Patch Kubernetes nodes
  hosts: dreamcompute
  gather_facts: true
  become: true
  serial: 1
  tags: dreamcompute_patch
  vars:
  # Configure access to internal network hosts
    ansible_host: |-
      {{ hostvars['localhost']['dreamhost_access_ipv4'][inventory_hostname] }}

    # https://www.jeffgeerling.com/blog/2022/using-ansible-playbook-ssh-bastion-jump-host
    ansible_ssh_common_args: |-
      {{ '-o ProxyCommand="ssh -W %h:%p -q debian@' ~
         hostvars['localhost']['dreamhost_access_ipv4'][dreamhost_control_plane_endpoint] ~
         '"' }}

  roles:
    - us_wust.homeinfra.k8s_nodes_update

- name: Configure Kubernetes control nodes
  hosts: dreamcompute_control
  gather_facts: true
  become: true
  vars:
  # Configure access to internal network hosts
    ansible_host: |-
      {{ hostvars['localhost']['dreamhost_access_ipv4'][inventory_hostname] }}

    # https://www.jeffgeerling.com/blog/2022/using-ansible-playbook-ssh-bastion-jump-host
    ansible_ssh_common_args: |-
      {{ '-o ProxyCommand="ssh -W %h:%p -q debian@' ~
         hostvars['localhost']['dreamhost_access_ipv4'][dreamhost_control_plane_endpoint] ~
         '"' }}

  roles:
    - us_wust.homeinfra.k8s_nodes

- name: Configure Kubernetes worker nodes
  hosts: dreamcompute_worker
  gather_facts: true
  become: true
  vars:
  # Configure access to internal network hosts
    ansible_host: |-
      {{ hostvars['localhost']['dreamhost_access_ipv4'][inventory_hostname] }}

    # https://www.jeffgeerling.com/blog/2022/using-ansible-playbook-ssh-bastion-jump-host
    ansible_ssh_common_args: |-
      {{ '-o ProxyCommand="ssh -W %h:%p -q debian@' ~
         hostvars['localhost']['dreamhost_access_ipv4'][dreamhost_control_plane_endpoint] ~
         '"' }}

  roles:
    - us_wust.homeinfra.k8s_nodes

- name: Apply QNAP NAS configuration
  hosts: nas
  gather_facts: true
  become: true
  roles:
    - us_wust.homeinfra.nas

...
