---

- name: Apply DreamCompute configuration
  hosts: dreamcompute
  become: false
  gather_facts: true
  roles:
    - us_wust.homeinfra.dreamcompute

- name: Apply QNAP NAS configuration
  hosts: nas
  gather_facts: true
  roles:
    - us_wust.homeinfra.nas

...
