---

- name: Apply DreamHost Server configuration
  hosts: dreamhost_servers
  become: false
  gather_facts: true
  roles:
    - us_wust.homeinfra.dreamhost

- name: Apply QNAP NAS configuration
  hosts: nas
  gather_facts: true
  roles:
    - us_wust.homeinfra.nas

...
