---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    homeinfra_sidecar_hostname: testbox

  tasks:
    # Make sure that bareos and other services can resolve the hostname
    - name: Insert a line into /etc/hosts for the VM
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ ansible_host }} {{ homeinfra_sidecar_hostname }}"

    - name: Run sidecar VM tasks
      ansible.builtin.import_role:
        name: us_wust.homeinfra.sidecar
      vars:
        homeinfra_sidecar_network_adapters:
          - macaddress: "{{ lookup('env', 'HOMEINFRA_TEST_VM_PRIMARY_MAC_ADDRESS') }}"
          - macaddress: "{{ lookup('env', 'HOMEINFRA_TEST_VM_SECONDARY_MAC_ADDRESS') }}"
            bootproto: static
            address: "{{ lookup('env', 'HOMEINFRA_TEST_VM_SECONDARY_IP_ADDRESS') }}"
            prefixlen: "{{ lookup('env', 'HOMEINFRA_TEST_VM_SECONDARY_PREFIXLEN') }}"

...
