---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: Run sidecar VM tasks
      ansible.builtin.import_role:
        name: us_wust.hostinfra.sidecar
      vars:
        hostinfra_sidecar_ipv4:
          # pick the address reported / assigned by VMware Fusion, but
          # reconfigure it as static
          address: "{{ ansible_host }}"
          # it always seems to be a /24; assume that
          prefixlen: 24
          # strip the last (host) octet, and replace it with a 2
          # e.g., 192.168.45.67 -> 192.168.45.2
          default_gateway: "{{ ansible_host | regex(\"^(.*\\.)(.*)$\", \"\\1.2\") }}"
          dns_servers:
            - "{{ ansible_host | regex(\"^(.*\\.)(.*)$\", \"\\1.2\") }}"
          dns_searchlist: []

...
