---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  # no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Identify virtual machines in VMware Workstation Pro / Fusion Pro
      qsypoq.vmware_desktop.unix_vmware_desktop_vminfos:
        username: "{{ lookup('env', 'HOMEINFRA_TEST_API_USERNAME') }}"
        password: "{{ lookup('env', 'HOMEINFRA_TEST_API_PASSWORD') }}"
        api_url: "{{ lookup('env', 'HOMEINFRA_TEST_API_URL') }}"
        api_port: "{{ lookup('env', 'HOMEINFRA_TEST_API_PORT') }}"
      register: homeinfra_test_vms

    - name: Identify the specific VM in question
      ansible.builtin.set_fact:
        homeinfra_test_vm: "{{ homeinfra_test_vms.msg | selectattr('path', 'match', \".*\\/\" ~ lookup('env', 'HOMEINFRA_TEST_VMNAME') ~ \"\\.vmx$\") | first }}"

    - name: Shut down the virtual machine
      qsypoq.vmware_desktop.unix_vmware_desktop_power:
        target_vm: "{{ homeinfra_test_vm.id }}"
        username: "{{ lookup('env', 'HOMEINFRA_TEST_API_USERNAME') }}"
        password: "{{ lookup('env', 'HOMEINFRA_TEST_API_PASSWORD') }}"
        api_url: "{{ lookup('env', 'HOMEINFRA_TEST_API_URL') }}"
        api_port: "{{ lookup('env', 'HOMEINFRA_TEST_API_PORT') }}"
        # This needs to be a string, so YAML doesn't treat it as a bool
        state: "off"

    - name: Revert the virtual machine to the known-good snapshot
      ansible.builtin.command: "'/Applications/VMware Fusion.app/Contents/Public/vmrun' -T fusion revertToSnapshot \"{{ homeinfra_test_vm.path }}\" \"{{ lookup('env', 'HOMEINFRA_TEST_VM_SNAPSHOT_NAME') }}\""

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config
      ansible.builtin.set_fact:
        instance_conf: {}

    - name: Dump instance config
      ansible.builtin.copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
        mode: "0600"
      when: server.changed | default(false) | bool  # noqa no-handler
