---
dependency:
  name: galaxy
  enabled: True
  options:
    # The molecule default is collections.yml, but Ansible Galaxy still seems
    # to prefer requirements.yml, so ?
    requirements-file: requirements.yml

platforms:
  - name: instance
