---
# Lay down initialization scripts for PostgreSQL

- name: If initializing, lay down initialization scripts for PostgreSQL
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ nas_container_folder }}/user-config/database/initdb.d/{{ item | basename }}"
    mode: "0755"
  loop: "{{ (role_path ~ '/files/database/initdb.d/*') | ansible.builtin.fileglob }}"
  when: 'nas_postgres_initialization'

- name: If not initializing, delete unwanted initialization scripts for PostgreSQL
  ansible.builtin.file:
    path: "{{ nas_container_folder }}/user-config/database/initdb.d/{{ item | basename }}"
    state: absent
  loop: "{{ (role_path ~ '/files/database/initdb.d/*') | ansible.builtin.fileglob }}"
  when: 'not nas_postgres_initialization'

