---
# Lay down files containing secrets

- name: Lay down files containing secrets
  ansible.builtin.template:
    src: "database/{{ item | basename }}.txt.j2"
    dest: "{{ nas_container_folder }}/user-config/{{ item }}.txt"
    mode: "0600"
  loop:
    - database/postgres-bacula-password
    - database/postgres-password
