---
# Lay down files containing secrets

- name: Lay down files containing secrets
  ansible.builtin.template:
    src: "{{ item }}.txt.j2"
    dest: "{{ nas_container_folder }}/user-config/{{ item }}.txt"
    mode: "0600"
  loop:
    - postgres-password
