---
# handlers for us_wust.homeinfra.sidecar_bareos

- name: Restart bareos Director service
  ansible.builtin.service:
    name: bareos-dir.service
    state: restarted

- name: Restart bareos Storage service
  ansible.builtin.service:
    name: bareos-sd.service
    state: restarted

...
