apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose -f ./Documents/ejbca/bacula-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: bacula-dir
  name: bacula-dir
spec:
  ports:
    - name: "9101"
      port: 9101
      targetPort: 9101
  selector:
    io.kompose.service: bacula-dir
