apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose -f ./Documents/ejbca/bacula-compose.yaml convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: bacula-sd
  name: bacula-sd
spec:
  ports:
    - name: "9103"
      port: 9103
      targetPort: 9103
  selector:
    io.kompose.service: bacula-sd
