---
# Set up FirewallD to allow additional services

- name: Set up FirewallD for bareos incoming ports
  ansible.builtin.firewalld:
    permanent: yes
    immediate: yes
    port: "{{ homeinfra_sidecar_firewall_port }}/tcp"
    state: enabled
    zone: public
  loop_control:
    loop_var: homeinfra_sidecar_firewall_port
  loop:
    - 9101 # bacula-dir
    - 9103 # bacula-sd

...
