---

- name: Install useful packages for troubleshooting, etc.
  ansible.builtin.package:
    name: "{{ homeinfra_sidecar_package }}"
    state: present
  loop_control:
    loop_var: homeinfra_sidecar_package
  loop:
    - net-tools
    - tcpdump

- name: Update packages to the latest version
  ansible.builtin.package:
    name: "*"
    state: latest
  register: sidecar_installed_packages

- name: Reboot the system if packages were updated
  ansible.builtin.reboot:
  when: "sidecar_installed_packages is changed"

...
