name: qnap-nas
version: "3"

services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    volumes:
      - ddns_data:/updater/data
      - /share/CE_CACHEDEV5_DATA/Secrets/ddns-updater/config:/updater/config
    environment:
      - PERIOD=1h
      - HTTP_TIMEOUT=10s
      - SERVER_ENABLED=no
      - CONFIG_FILEPATH=/updater/config/config.json
    restart: on-failure:3

  # https://github.com/wmnnd/nginx-certbot
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - nginx_data:/etc/nginx/conf.d
      - /share/CE_CACHEDEV5_DATA/Secrets/letsencrypt:/etc/letsencrypt
      - nginx_www:/var/www
    ports:
      - "10080:80"
      - "10443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # https://github.com/wmnnd/nginx-certbot
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /share/CE_CACHEDEV5_DATA/Secrets/letsencrypt:/etc/letsencrypt
      - nginx_www:/var/www
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  ddns_data:
  nginx_data:
  nginx_www:
