---
# Update DreamHost DNS records to match

- name: Retrieve DreamHost access IPs from prior localhost play
  ansible.builtin.set_fact:
    dreamhost_access_ipv4: |-
      {{ hostvars['localhost']['dreamhost_access_ipv4'][inventory_hostname] }}
    dreamhost_access_ipv6: |-
      {{ hostvars['localhost']['dreamhost_access_ipv6'][inventory_hostname] }}

- name: For convenience (with new hosts), go ahead and overwrite ansible_host
  ansible.builtin.set_fact:
    ansible_host: "{{ dreamhost_access_ipv4 }}"

- name: Retrieve DNS records
  ansible.builtin.uri:
    url: 'https://api.dreamhost.com/?key={{ dreamhost_dns_api_key }}&cmd=dns-list_records'
    return_content: true
  register: dreamhost_dns_record_listing
  # This is a read-only API endpoint
  check_mode: false
  changed_when: false

- name: Delete and recreate (if necessary) the primary DNS name
  ansible.builtin.include_tasks: dns_overwrite.yml
  vars:
    k8s_nodes_dns_overwrite_name: "{{ inventory_hostname }}"

- name: Delete and recreate (if necessary) the control-plane DNS name
  ansible.builtin.include_tasks: dns_overwrite.yml
  vars:
    k8s_nodes_dns_overwrite_name: "{{ dreamhost_control_plane_endpoint }}"
  when: "k8s_nodes_is_control"
