---
# Director resources for centralized control
# Also the Console installation (bconsole)

- ansible.builtin.include_role:
    name: robertdebock.bareos.bareos_dir
  vars:
    bareos_dir_hostname: "{{ ansible_fqdn }}"
    bareos_dir_password: "{{ homeinfra_sidecar_bareos_config.director_password }}"
    # TODO: Fix this to enable client-initiated backup/restore over the Internet
    bareos_dir_tls_enable: no
    bareos_dir_tls_verify_peer: no

    bareos_dir_filesets:
      - name: QNAP Sidecar
        description: Various SMB-mounted dirs from the QNAP
        include:
          files: "{{ homeinfra_sidecar_smb_mounts | map(attribute='destination') | list }}"
          options:
            signature: XXH128
            compression: LZ4
        exclude:
          # Append "/@Recently-Snapshot" to each SMB mountpoint
          files: "{{ homeinfra_sidecar_smb_mounts | map(attribute='destination') | map('regex_replace', '$', '/@Recently-Snapshot') | list }}"

    bareos_dir_storages:
      - name: File
        address: "{{ ansible_fqdn }}"
        password: "{{ homeinfra_sidecar_bareos_config.sidecar_sd_password }}"
        device: FileStorage
        media_type: File
        tls_enable: no
        tls_verify_peer: no

    bareos_dir_clients: "{{ homeinfra_sidecar_bareos_config.clients | default([]) }}"

- ansible.builtin.include_role:
    name: robertdebock.bareos.bareos_console
  vars:
    bareos_console_directors:
      - name: bareos-dir
        address: localhost
        password: "{{ homeinfra_sidecar_bareos_config.director_password }}"
        description: "Bareos Console credentials for local Director"
        tls_enable: no
        tls_verify_peer: no

- name: Cleanup some extraneous/unwanted configuration files
  ansible.builtin.file:
    path: "/etc/bareos/bareos-dir.d/{{ homeinfra_sidecar_bareos_director_file }}"
    state: absent
  loop:
    - job/backup-bareos-fd.conf
    - storage/Tape.conf.example
  loop_control:
    loop_var: homeinfra_sidecar_bareos_director_file
  notify: Restart bareos Director service

...
