---
# File Daemon / Client on the sidecar VM

- ansible.builtin.include_role:
    name: robertdebock.bareos.bareos_fd
  vars:
    bareos_fd_hostname: "{{ ansible_fqdn }}"
    bareos_fd_tls_enable: no
    bareos_fd_tls_verify_peer: no
    bareos_fd_encryption_enabled: true
    bareos_fd_encryption_private_key: "{{ homeinfra_sidecar_bareos_config.pki_fd_private }}"
    bareos_fd_encryption_master_public_key: "{{ homeinfra_sidecar_bareos_config.pki_master_public }}"

    bareos_fd_directors:
      - name: "{{ ansible_fqdn }}"
        password: "{{ homeinfra_sidecar_bareos_config.sidecar_fd_password }}"
        monitor: no
        connection_from_client_to_director: no
        connection_from_director_to_client: yes
        tls_enable: no
        tls_verify_peer: no

    bareos_fd_messages:
      - name: bareos-standard-msg
        description: "Send relevant messages to the Director."
        director:
          server: bareos-dir
          messages:
            - all
            - "!skipped"
            - "!restored"
        description: "Send relevant messages to the Director."
        append:
          file: "/var/log/bareos/bareos.log"
          messages:
            - all
            - "!skipped"
            - "!terminate"
        console:
          - all
          - "!skipped"
          - "!saved"

...
