---
# Storage Daemon for interfacing with volumes

- ansible.builtin.include_role:
    name: robertdebock.bareos.bareos_sd
  vars:
    bareos_sd_hostname: sidecar-sd
    # TODO: Fix this to enable client-initiated backup/restore over the Internet
    bareos_sd_tls_enable: no
    bareos_sd_tls_verify_peer: no

    bareos_sd_devices:
      - name: FileStorage
        media_type: File
        archive_device: /mnt/BareOS
        label_media: true
        random_access: true
        automatic_mount: true
        removable_media: false
        always_open: false

    bareos_sd_directors:
      - name: "{{ ansible_fqdn }}"
        password: "{{ homeinfra_sidecar_bareos_config.sidecar_sd_password }}"
        enabled: true
        tls_enable: no
        tls_verify_peer: no

- name: Cleanup some extraneous/unwanted configuration files
  ansible.builtin.file:
    path: "/etc/bareos/bareos-sd.d/{{ homeinfra_sidecar_bareos_storage_file }}"
    state: absent
  loop:
    - autochanger/autochanger-0.conf.example
    - device/tapedrive-0.conf.example
    - director/bareos-dir.conf
  loop_control:
    loop_var: homeinfra_sidecar_bareos_storage_file
  notify: Restart bareos Storage service

...
