---
# Configure DreamCompute resources

- name: Set up DreamCompute networking infrastructure
  ansible.builtin.import_tasks: network.yml

- name: Set up individual DreamCompute instances
  ansible.builtin.include_tasks: instance.yml
  loop_control:
    loop_var: dreamhost_instance_name
  loop: "{{ groups['k8s_nodes'] }}"
