apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: {{ .Values.bwsecret.name | quote }}
spec:
  organizationId: {{ .Values.bwsecret.project_id | quote }}
  secretName: {{ .Values.bwsecret.name | quote }}
  map:
#  - bwSecretId: 6c230265-d472-45f7-b763-b11b01023ca6
#     secretKeyName: container__registry__secret
#  - bwSecretId: d132a5ed-12bd-49af-9b74-b11b01025d58
#     secretKeyName: test__secret__2
  authToken:
    secretName: bw-auth-token
    secretKey: token
