apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: {{ .Values.bwsecret.name | quote }}
spec:
  organizationId: {{ .Values.bwsecret.organization_id | quote }}
  secretName: {{ .Values.bwsecret.name | quote }}
  map:
    - bwSecretId: c0b20ee2-83e2-405d-9cf6-b31300660144
      secretKeyName: bitwarden_sm_sample
  authToken:
    secretName: bw-auth-token
    secretKey: token
