---
# Variables for my QNAP network-attached storage server

# This path is provided by the official Python3 app from the QNAP Store
# https://forum.qnap.com/viewforum.php?f=217
ansible_python_interpreter: /share/CACHEDEV1_DATA/.qpkg/Python3/opt/python3/bin/python3.12

# Calling user is expected to have configured SSH keys with ssh-copy-id

nas_bacula_folder: /share/Bacula
nas_container_folder: /share/Container

# Secret named "qnap_postgres_password"
nas_postgres_password: "{{ lookup('bitwarden.secrets.lookup', 'aa4b1bad-0a79-401a-9d50-b28d01434ba3') }}"

# Secret named "qnap_postgres_bacula_password"
nas_postgres_bacula_password: "{{ lookup('bitwarden.secrets.lookup', '1314e795-3ebf-428d-9c17-b28d0150789a') }}"

# Secret named "qnap_bacula_console"
nas_bacula_console_password: "{{ lookup('bitwarden.secrets.lookup', '085d6022-22cc-4783-8dfd-b28f00707740') }}"

# Secret named "qnap_bacula_dir_sd"
nas_bacula_dir_sd_password: "{{ lookup('bitwarden.secrets.lookup', '146a578b-18a4-4149-8ecd-b28f0085e2fe') }}"

nas_bacula_letsencrypt_fqdn: w5tower.wust.us
nas_bacula_fqdn: bacula.wust.us
