---
name: bacula-on-jilliumz

services:
  # https://hub.docker.com/_/postgres
  postgresql:
    image: postgres
    restart: on-failure:3
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
    volumes:
      - /data/postgresql/data:/var/lib/postgresql
      - /data/postgresql/initdb.d:/docker-entrypoint-initdb.d:ro
    secrets:
      - postgres-bacula-password
      - postgres-password

  bacula-dir:
    image: liverwust/bacula-dir:bookworm-15.0.3-1
    restart: on-failure:3
    ports:
      - 9101:9101
    volumes:
      - /data/bacula/dir/archive:/opt/bacula/archive
      - /data/bacula/dir/bsr:/opt/bacula/bsr
      - /data/bacula/dir/etc:/opt/bacula/etc
      - /data/bacula/dir/log:/opt/bacula/log
      - /data/bacula/dir/working:/opt/bacula/working

  bacula-sd:
    image: liverwust/bacula-sd:bookworm-15.0.3-1
    restart: on-failure:3
    ports:
      - 9103:9103
    volumes:
      - /data/bacula/sd/archive:/opt/bacula/archive
      - /data/bacula/sd/bsr:/opt/bacula/bsr
      - /data/bacula/sd/etc:/opt/bacula/etc
      - /data/bacula/sd/log:/opt/bacula/log
      - /data/bacula/sd/working:/opt/bacula/working

secrets:
  # Note: with Docker Desktop, it is necessary to add one of these parent
  # directories to the list of File Sharing locations:
  # https://docs.docker.com/desktop/settings-and-maintenance/settings/#file-sharing

  # The superuser password for the postgresql database.
  postgres-password:
    file: /data/bacula/db/secrets/postgres-password.txt

  # The user password for the Bacula user accessing PostgreSQL
  postgres-bacula-password:
    file: /data/bacula/db/secrets/postgres-bacula-password.txt
