---
apiVersion: v1
kind: Service
metadata:
  name: ejbca-database
  labels:
    app: ejbca-database
  namespace: ejbca
spec:
  ports:
    - port: 3306
  selector:
    app: ejbca-database

---
apiVersion: v1
kind: Service
metadata:
  name: ejbca-node1
  labels:
    app: ejbca-node1
  namespace: ejbca
spec:
  ports:
    - port: 80
      name: ejbca-node1-http
    - port: 443
      name: ejbca-node1-https
  selector:
    app: ejbca-node1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejbca-database
  labels:
    app: ejbca-database
  namespace: ejbca
spec:
  selector:
    matchLabels:
      app: ejbca-database
  template:
    metadata:
      labels:
        app: ejbca-database
    spec:
      containers:
        - name: ejbca-database
          image: library/mariadb:latest
          ports:
            - containerPort: 3306
          envFrom:
            - prefix: MYSQL_
              secretRef:
                name: ejbca-database-secret
          volumeMounts:
            - name: ejbca-database
              mountPath: /var/lib/mysql
      volumes:
        - name: ejbca-database
          persistentVolumeClaim:
            claimName: ejbca-database

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejbca-node1
  labels:
    app: ejbca-node1
  namespace: ejbca
spec:
  selector:
    matchLabels:
      app: ejbca-node1
  template:
    metadata:
      labels:
        app: ejbca-node1
    spec:
      containers:
        - name: ejbca-node1
          image: keyfactor/ejbca-ce:latest
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: ejbca-node1-plain
            - secretRef:
                name: ejbca-node1-secret

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ejbca-database
  namespace: ejbca
spec:
  accessModes:
    - ReadWriteOncePod
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi

